### ISSUE TITLE
Từ điển thuật ngữ

### ISSUE THREAD

**Issue by cuonganh** [cuonganh/Toeic#5]
Mô tả các thuật ngữ sử dụng trong hệ thống.

**Comment by trinhquocdai1102** [comment]
[Từ điển thuật ngữ.docx](https://github.com/cuonganh/Toeic/files/4444733/T.di.n.thu.t.ng.docx)

**Comment by cuonganh** [comment]
Checked

**Comment by trinhquocdai1102** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/62043209/80126549-76670e80-85bd-11ea-9fd9-e0e0618fa8f9.png)
